<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-S2QR9LR" failures="1" tests="3" name="Test" time="44.148" errors="0" timestamp="2023-03-04T17:18:39 CET">
  <testcase classname="testcases.LoginTest" name="LogiFailureTest" time="12.423">
    <failure type="java.lang.AssertionError" message="expected [New message] but found [The email or password you have entered is invalid.]">
      <![CDATA[java.lang.AssertionError: expected [New message] but found [The email or password you have entered is invalid.]
at testcases.LoginTest.LogiFailureTest(LoginTest.java:30)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- LogiFailureTest -->
  <testcase classname="testcases.LoginTest" name="LoginSuccessTest" time="10.511"/>
  <testcase classname="testcases.LoginTest" name="LoginTest12" time="11.48"/>
</testsuite> <!-- Test -->
